version: '3.6'

services:
  frontend:
    restart: always
    image: "ndexnetwork/npro:v3.1.4"
    volumes:
      - ../config/frontend/env.js:/usr/share/nginx/html/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:www.quantaex.com"
      traefik.port: 3000

  tower:
    restart: always
    image: "nexbitio/tower-2.3s"
    volumes:
      - ../config/frontend/tower.js:/home/app/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/tower;Host:www.quantaex.com"
      traefik.port: 8080

